package config

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

// DetectedConfig represents an existing configuration file found in the project directory.
type DetectedConfig struct {
	Type string // "compose", "devcontainer", "dockerfile"
	Path string
}

// DetectExistingConfigs scans a directory for known configuration files.
func DetectExistingConfigs(dir string) []DetectedConfig {
	candidates := []struct {
		typ  string
		path string
	}{
		{"compose", "docker-compose.yml"},
		{"compose", "docker-compose.yaml"},
		{"devcontainer", ".devcontainer/devcontainer.json"},
		{"dockerfile", "Dockerfile"},
	}

	var found []DetectedConfig
	for _, c := range candidates {
		full := filepath.Join(dir, c.path)
		if _, err := os.Stat(full); err == nil {
			found = append(found, DetectedConfig{Type: c.typ, Path: c.path})
		}
	}
	return found
}

// WriteConfig marshals a DevboxConfig to YAML and writes it to path.
// Returns an error if the file already exists (uses O_EXCL for atomic check).
func WriteConfig(cfg *DevboxConfig, path string) error {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("failed to marshal config: %w", err)
	}

	header := "# devbox.yaml — Generated by devbox init\n\n"
	content := []byte(header + string(data))

	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0644)
	if err != nil {
		if os.IsExist(err) {
			return fmt.Errorf("%s already exists", path)
		}
		return fmt.Errorf("failed to create %s: %w", path, err)
	}
	defer f.Close()

	_, err = f.Write(content)
	return err
}

// composeFile represents the relevant parts of a docker-compose.yml.
type composeFile struct {
	Services map[string]composeService `yaml:"services"`
}

// composeService represents a single service in a docker-compose.yml.
type composeService struct {
	Image string   `yaml:"image"`
	Ports []string `yaml:"ports"`
}

// ConvertFromCompose parses a docker-compose.yml and returns a partially-filled DevboxConfig.
// Name and Server are left empty for the caller to fill.
func ConvertFromCompose(composePath string) (*DevboxConfig, error) {
	data, err := os.ReadFile(composePath)
	if err != nil {
		return nil, fmt.Errorf("failed to read compose file: %w", err)
	}

	var cf composeFile
	if err := yaml.Unmarshal(data, &cf); err != nil {
		return nil, fmt.Errorf("failed to parse compose file: %w", err)
	}

	if len(cf.Services) == 0 {
		return nil, fmt.Errorf("no services found in %s", composePath)
	}

	cfg := &DevboxConfig{
		Ports: make(map[string]int),
	}

	for name, svc := range cf.Services {
		if svc.Image == "" {
			fmt.Fprintf(os.Stderr, "Warning: skipping service %q (no image, build-based)\n", name)
			continue
		}
		cfg.Services = append(cfg.Services, svc.Image)

		for _, p := range svc.Ports {
			hostPort := parseHostPort(p)
			if hostPort > 0 {
				cfg.Ports[name] = hostPort
			}
		}
	}

	if len(cfg.Services) == 0 {
		return nil, fmt.Errorf("no image-based services found in %s", composePath)
	}

	return cfg, nil
}

// parseHostPort extracts the host port from a compose port mapping like "3306:3306" or "8080:80".
func parseHostPort(mapping string) int {
	parts := strings.SplitN(mapping, ":", 2)
	if len(parts) == 0 {
		return 0
	}
	port, err := strconv.Atoi(strings.TrimSpace(parts[0]))
	if err != nil {
		return 0
	}
	return port
}

// PromptString prints a prompt with an optional default and reads a line from the scanner.
func PromptString(w io.Writer, scanner *bufio.Scanner, label string, defaultVal string) string {
	if defaultVal != "" {
		fmt.Fprintf(w, "%s [%s]: ", label, defaultVal)
	} else {
		fmt.Fprintf(w, "%s: ", label)
	}
	if scanner.Scan() {
		input := strings.TrimSpace(scanner.Text())
		if input != "" {
			return input
		}
	}
	return defaultVal
}

// PromptRequired prints a prompt and loops until a non-empty value is provided.
// Returns empty string if stdin reaches EOF without providing a value.
func PromptRequired(w io.Writer, scanner *bufio.Scanner, label string) string {
	for {
		fmt.Fprintf(w, "%s (required): ", label)
		if !scanner.Scan() {
			return ""
		}
		input := strings.TrimSpace(scanner.Text())
		if input != "" {
			return input
		}
	}
}

// ParseCommaSeparated splits a comma-separated string into trimmed, non-empty items.
func ParseCommaSeparated(input string) []string {
	if strings.TrimSpace(input) == "" {
		return nil
	}
	parts := strings.Split(input, ",")
	var result []string
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" {
			result = append(result, p)
		}
	}
	return result
}

// ParsePortMappings parses comma-separated key:value port mappings like "app:8080,db:3306".
func ParsePortMappings(input string) map[string]int {
	items := ParseCommaSeparated(input)
	if len(items) == 0 {
		return nil
	}
	ports := make(map[string]int)
	for _, item := range items {
		parts := strings.SplitN(item, ":", 2)
		if len(parts) != 2 {
			continue
		}
		port, err := strconv.Atoi(strings.TrimSpace(parts[1]))
		if err != nil {
			continue
		}
		ports[strings.TrimSpace(parts[0])] = port
	}
	if len(ports) == 0 {
		return nil
	}
	return ports
}
